#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

[ -n "$CI" ] && exit 0

BASE_PATH="$(
  cd "$(dirname "$0")/" >/dev/null 2>&1
  pwd -P
)"

yarn run build && git add $BASE_PATH/../dist/*
npx --no-install lint-staged
yarn run lint
yarn run format:check
