name: "Commit"
on:
  pull_request:
  push:
    branches:
      - "main"
      - "releases/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "12"

      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore dependencies cache
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --silent

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build

      # - name: Unit tests
      #   run: yarn run test

  test-action:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        ng: ["7", "8", "9", "10", "11"]
        include:
          - ng: "7"
            node: "10"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node || '12' }}
      - uses: ./
        env:
          ACTIONS_RUNNER_DEBUG: true
        with:
          version: ${{ matrix.ng }}
          sourceDir: "mocks/ng-in-viewport"
